# APAGUE TUDO O QUE TEM E COLE ESTE BLOCO COM CUIDADO:

spring.application.name=pactos

# Verifique muito bem este Host e esta Porta. Não deixe nenhum espaço!
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_G3fxQOvgL2nA5oUP-ks@db-fichapactos-pactosficha.b.aivencloud.com:12817/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_G3fxQOvgL2nA5oUP-ks

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

google.recaptcha.secret=6LflIIAsAAAAAJmTBNc9KAnoJU_ZnEylo0gQsV3P